In [1]:
import os, sys, numpy as np, matplotlib.pyplot as plt

if os.path.basename(os.getcwd()) == "notebooks":
    os.chdir("..")
print(f"Current path: {os.getcwd()}")
sys.path.append('./')

from environments.complementary import ComplementaryPricingEnvironment

Current path: /Users/marcomussi/git/PricingComplementaryProducts


In [2]:
horizon = 10
n_products = 3
n_actions = 5
n_baskets = 100
products_probs = np.array([0.5, 0.5, 0.5])
alpha = 1.0 # 1 revenue, 0 profit
mc_ep = 10000

margins = np.linspace(0.1, 0.9, n_actions)
margins_to_idx = {margins[i]: i for i in range(n_actions)}
margins = margins.reshape(1, n_actions)
margins_env = np.repeat(margins, n_products, axis=0)

demands = np.array([[0.7, 0.7, 0.3, 0.2, 0.1], [0.7, 0.6, 0.6, 0.4, 0.1], [0.7, 0.6, 0.6, 0.5, 0.3]])
demands_compl = np.repeat(demands, 2, axis=1).reshape(n_products, n_actions, 2)
demands_compl[1, :, 1] = np.array([0.95, 0.9, 0.7, 0.6, 0.4]) # enhanced demand for product 1
demands_compl[2, :, 1] = np.array([0.95, 0.9, 0.7, 0.6, 0.4]) # enhanced demand for product 2

graph_dict = {0: [], 1: [], 2: []} # product 0, 1, 2 are all leaders/independent
env = ComplementaryPricingEnvironment(n_products, n_actions, margins_env, demands_compl, n_baskets, 
                                      products_probs, alpha, graph_dict, mc_ep=mc_ep, seed=0)
vals = env.compute_values()
for i in env.leaders_lst:
    print(f"Optimal values for leader {i}:")
    print(np.round(vals[i], 3))

graph_dict = {0: [1, 2]} # product 0 is leader of products 1 and 2
env = ComplementaryPricingEnvironment(n_products, n_actions, margins_env, demands_compl, n_baskets, 
                                      products_probs, alpha, graph_dict, mc_ep=mc_ep, seed=0)
vals = env.compute_values()
for i in env.leaders_lst:
    print(f"Optimal values for leader {i}:")
    print(np.round(vals[i], 3))

Optimal values for leader 0:
[0.094 0.454 0.225 0.169 0.095]
Optimal values for leader 1:
[0.095 0.391 0.451 0.34  0.095]
Optimal values for leader 2:
[0.286 0.39  0.451 0.425 0.286]
Optimal values for leader 0:
[[0.512 0.914 1.012 0.886 0.514]
 [1.1   1.508 1.46  1.398 1.1  ]
 [0.721 1.123 1.17  1.067 0.719]
 [0.626 1.028 1.1   0.986 0.625]
 [0.514 0.912 1.01  0.886 0.513]]
