In [2]:
import os, sys, numpy as np

if os.path.basename(os.getcwd()) == "notebooks":
    os.chdir("..")
print(f"Current path: {os.getcwd()}")
sys.path.append('./')

from solvers.integer_optimizers import complementary_products

V_mx = np.array([
    [10, 20, 30, 40, 50, 60],
    [10, 20, 30, 40, 50, 60],
    [30, 50, 30, 40, 50, 60],
    [10, 20, 30, 40, 80, 60],
    [10, 20, 30, 40, 50, 60],
    [10, 20, 30, 40, 50, 60]
])

x_vals, y_vals = complementary_products(V_mx, verbose=True)

Current path: /Users/marcomussi/git/PricingComplementaryProducts
Starting Solver with input matrix: 
[[10 20 30 40 50 60]
 [10 20 30 40 50 60]
 [30 50 30 40 50 60]
 [10 20 30 40 80 60]
 [10 20 30 40 50 60]
 [10 20 30 40 50 60]]
Solver Status: OPTIMAL
Objective value: 290.0

Decision Variables (x[i][j]):
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 1 1 0 0 0]
 [0 0 0 1 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 1]]

Binary Variables y:
[1 1 0 0 1 1]
